FROM openjdk:17               # FROM<image>
VOLUME /tmp                   # Temporary location to run
EXPOSE 8080                   # Provide port number
ADD target/student-management-system-0.0.1-SNAPSHOT.jar student-management-system-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/student-management-system-0.0.1-SNAPSHOT.jar "]